version: "3.8"

services:
  asf:
    container_name: ArchiSteamFarm
    image: justarchi/archisteamfarm:latest
    restart: always
    ports:
      - 1242:1242
    volumes:
      - ./ASF/config:/app/config
      - ./ASF/logs:/app/logs
      - ./ASF/plugins:/app/plugins

  db:
    container_name: heckgaming-db
    image: mariadb:latest
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    env_file:
      - .env

  bot:
    container_name: heckgaming-bot
    image: heckgaming-discord-bot
    build: .
    restart: always
    depends_on:
      - asf
      - db
    volumes:
      - ./config:/app/config
      - ./bot.log:/app/bot.log

  adminer:
    container_name: heckgaming-adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
