version: '3.8'

services:
  asf:
    container_name: archi-steam-farm
    image: justarchi/archisteamfarm:latest
    restart: unless-stopped
    ports:
      - 1242:1242
    volumes:
      - ./ASF/config:/app/config
      - ./ASF/logs:/app/logs
      - ./ASF/plugins:/app/plugins
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  bot:
    container_name: asf-bot
    image: asf-discord-bot
    build: .
    restart: unless-stopped
    depends_on:
      - asf
    volumes:
      - ./config:/app/config
      - ./bot.log:/app/bot.log
