version: '3.8'

services:
  asf:
    container_name: archi-steam-farm
    image: justarchi/archisteamfarm:latest
    restart: always
    ports:
      - 1242:1242
    volumes:
      - ./ASF/config:/app/config
      - ./ASF/logs:/app/logs
      - ./ASF/plugins:/app/plugins
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  mariadb:
    container_name: heckgaming-mariadb
    image: mariadb:latest
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    env_file:
      - .env

  bot:
    container_name: heckgaming-bot
    image: heckgaming-discord-bot
    build: .
    restart: always
    depends_on:
      - asf
      - mariadb
    volumes:
      - ./config:/app/config
      - ./bot.log:/app/bot.log
