name: asf-discord-bot-dev
services:
  asf:
    container_name: archi-steam-farm
    image: justarchi/archisteamfarm:latest
    labels:
      - 'com.centurylinklabs.watchtower.enable=false'
    ports:
      - 1242:1242
    restart: unless-stopped
    volumes:
      - ./ASF/config:/app/config
      - ./ASF/logs:/app/logs
      - ./ASF/plugins:/app/plugins
  bot:
    build: .
    container_name: asf-bot-dev
    depends_on:
      - asf
    image: asf-discord-bot-dev:latest
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
