export const strings: { [index: string]: string } = {
    invalidChannel: 'You cannot run that command in this channel.',
    noCommandPermission: 'You do not have permission to use that command.',
    noBotPermission: 'No permission.',
    requestFailed: 'The request was made but no response was received.',
    badResponse: 'The received response does not indicate success.',
    unknownError: 'An unknown error has occurred.',
    tooManyArguments: 'Too many arguments have been supplied.'
};

export const descriptions: { [index: string]: string } = {
    '_2fa': "ASF: Get bots' 2FA",
    '_2fano': "ASF: Deny bots' confirmations",
    '_2faok': "ASF: Confirm bots' confirmations",
    'addlicense': 'ASF: Activate licenses on bots',
    'asf': 'ASF: Call any ASF command',
    'balance': "ASF: Get bots' wallet balance",
    'code': 'Rust: Generate a pseudo random unbiased 4 digit code',
    'convert': 'Any: Convert between 2 currencies',
    'farm': 'ASF: Restart idling on bots',
    'invite': 'Any: Get Discord invite URL',
    'level': "ASF: Get bots' level",
    'load': 'Any: Reload settings',
    'market': 'Any: Get Steam market listings',
    'nickname': "ASF: Change bot's nickname",
    'oa': 'ASF: Get bots owning an app',
    'permissions': 'Any: Get your own permissions',
    'ping': 'Any: Check latency',
    'play': 'ASF: Play games on bots',
    'points': "ASF: Get bots' points in Steam store",
    'privacy': "ASF: Set bots' privacy settings",
    'redeem': 'ASF: Redeem CD keys on bots',
    'reset': 'ASF: Stop playing games on bots',
    'remind': 'Any: Set a reminder',
    'resume': 'ASF: Resume idling on bots',
    'sa': 'ASF: Get status of all bots',
    'setvar': 'Any: Set a variable',
    'start': 'ASF: Start bots',
    'status': 'ASF: Get status of bots',
    'stop': 'ASF: Stop bots',
    'transfer': 'ASF: Transfer items between bots',
    'unpack': 'ASF: Unpack boosters on bots',
    'var': 'Any: Get a variable'
};
